export const headArmorData = [ {
    "id": 4,
    "light_level": 1498,
    "name": "Faded",
    "description": "Duis at velit eu est congue elementum.",
    "armor_slot": "head",
    "rarity": "rare",
    "mobility": 22,
    "intellect": 67,
    "resilience": 19,
    "recovery": 21,
    "strength": 20,
    "discipline": 91
  },
  {
    "id": 6,
    "light_level": 1507,
    "name": "Sub-Ex",
    "description": "Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
    "armor_slot": "head",
    "rarity": "rare",
    "mobility": 62,
    "intellect": 86,
    "resilience": 54,
    "recovery": 77,
    "strength": 64,
    "discipline": 67
  },
  {
    "id": 8,
    "light_level": 1410,
    "name": "Toughjoyfax",
    "description": "Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.",
    "armor_slot": "head",
    "rarity": "rare",
    "mobility": 74,
    "intellect": 51,
    "resilience": 63,
    "recovery": 88,
    "strength": 30,
    "discipline": 60
  },
  {
    "id": 11,
    "light_level": 1485,
    "name": "Asoka",
    "description": "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.",
    "armor_slot": "head",
    "rarity": "exotic",
    "mobility": 52,
    "intellect": 80,
    "resilience": 80,
    "recovery": 86,
    "strength": 37,
    "discipline": 65
  },
  {
    "id": 18,
    "light_level": 1539,
    "name": "Temp",
    "description": "Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.",
    "armor_slot": "head",
    "rarity": "legendary",
    "mobility": 51,
    "intellect": 45,
    "resilience": 98,
    "recovery": 61,
    "strength": 21,
    "discipline": 34
  }]

export const chestArmorData = [ {
    "id": 7,
    "light_level": 1564,
    "name": "Fixflex",
    "description": "Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.",
    "armor_slot": "chest",
    "rarity": "uncommon",
    "mobility": 64,
    "intellect": 19,
    "resilience": 93,
    "recovery": 33,
    "strength": 19,
    "discipline": 69
  },
  {
    "id": 10,
    "light_level": 1450,
    "name": "Tempsoft",
    "description": "Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.",
    "armor_slot": "chest",
    "rarity": "uncommon",
    "mobility": 63,
    "intellect": 55,
    "resilience": 85,
    "recovery": 92,
    "strength": 91,
    "discipline": 70
  },
  {
    "id": 17,
    "light_level": 1516,
    "name": "Cookley",
    "description": "Maecenas pulvinar lobortis est.",
    "armor_slot": "chest",
    "rarity": "uncommon",
    "mobility": 16,
    "intellect": 24,
    "resilience": 62,
    "recovery": 78,
    "strength": 72,
    "discipline": 51
  },
  {
    "id": 30,
    "light_level": 1473,
    "name": "Aerified",
    "description": "Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    "armor_slot": "chest",
    "rarity": "uncommon",
    "mobility": 15,
    "intellect": 77,
    "resilience": 92,
    "recovery": 16,
    "strength": 23,
    "discipline": 33
  }]

export const legsArmorData = [{
    "id": 13,
    "light_level": 1406,
    "name": "Zamit",
    "description": "Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.",
    "armor_slot": "legs",
    "rarity": "legendary",
    "mobility": 52,
    "intellect": 93,
    "resilience": 57,
    "recovery": 35,
    "strength": 91,
    "discipline": 86
  },
  {
    "id": 15,
    "light_level": 1438,
    "name": "Pannier",
    "description": "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.",
    "armor_slot": "legs",
    "rarity": "rare",
    "mobility": 29,
    "intellect": 100,
    "resilience": 49,
    "recovery": 58,
    "strength": 69,
    "discipline": 85
  },
  {
    "id": 16,
    "light_level": 1454,
    "name": "Bigtax",
    "description": "Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    "armor_slot": "legs",
    "rarity": "legendary",
    "mobility": 93,
    "intellect": 75,
    "resilience": 29,
    "recovery": 64,
    "strength": 59,
    "discipline": 91
  },
  {
    "id": 20,
    "light_level": 1560,
    "name": "Transcof",
    "description": "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.",
    "armor_slot": "legs",
    "rarity": "rare",
    "mobility": 46,
    "intellect": 99,
    "resilience": 27,
    "recovery": 56,
    "strength": 22,
    "discipline": 71
  }]

export const bootsArmorData = [ {
    "id": 5,
    "light_level": 1518,
    "name": "Tin",
    "description": "In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.",
    "armor_slot": "boots",
    "rarity": "exotic",
    "mobility": 65,
    "intellect": 99,
    "resilience": 49,
    "recovery": 21,
    "strength": 15,
    "discipline": 66
  },
  {
    "id": 12,
    "light_level": 1412,
    "name": "Ronstring",
    "description": "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.",
    "armor_slot": "boots",
    "rarity": "legendary",
    "mobility": 25,
    "intellect": 74,
    "resilience": 98,
    "recovery": 47,
    "strength": 45,
    "discipline": 37
  },
  {
    "id": 14,
    "light_level": 1598,
    "name": "Namfix",
    "description": "Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    "armor_slot": "boots",
    "rarity": "rare",
    "mobility": 28,
    "intellect": 24,
    "resilience": 27,
    "recovery": 91,
    "strength": 72,
    "discipline": 58
  },
  {
    "id": 25,
    "light_level": 1442,
    "name": "Job",
    "description": "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.",
    "armor_slot": "boots",
    "rarity": "rare",
    "mobility": 30,
    "intellect": 77,
    "resilience": 77,
    "recovery": 68,
    "strength": 69,
    "discipline": 100
  }
 ]

export const armsArmorData = [
    {
        "id": 1,
        "light_level": 1531,
        "name": "Sonsing",
        "description": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
        "armor_slot": "arms",
        "rarity": "rare",
        "mobility": 86,
        "intellect": 100,
        "resilience": 40,
        "recovery": 28,
        "strength": 61,
        "discipline": 30
      },
      {
        "id": 2,
        "light_level": 1400,
        "name": "Fintone",
        "description": "Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.",
        "armor_slot": "arms",
        "rarity": "exotic",
        "mobility": 97,
        "intellect": 54,
        "resilience": 26,
        "recovery": 60,
        "strength": 65,
        "discipline": 32
      },
      {
        "id": 3,
        "light_level": 1423,
        "name": "Alphazap",
        "description": "In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
        "armor_slot": "arms",
        "rarity": "legendary",
        "mobility": 97,
        "intellect": 50,
        "resilience": 26,
        "recovery": 86,
        "strength": 57,
        "discipline": 78
      },
      {
        "id": 9,
        "light_level": 1599,
        "name": "Voyatouch",
        "description": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.",
        "armor_slot": "arms",
        "rarity": "uncommon",
        "mobility": 32,
        "intellect": 41,
        "resilience": 19,
        "recovery": 42,
        "strength": 97,
        "discipline": 97
      }
]

export const classItemsData = [
    {
        "id": 51,
        "light_level": 1413,
        "name": "Flexidy",
        "description": "Praesent lectus.",
        "armor_slot": "class_item",
        "rarity": "exotic",
        "mobility": 92,
        "intellect": 73,
        "resilience": 33,
        "recovery": 59,
        "strength": 50,
        "discipline": 32
      },
      {
        "id": 52,
        "light_level": 1591,
        "name": "Bamity",
        "description": "Donec posuere metus vitae ipsum.",
        "armor_slot": "class_item",
        "rarity": "uncommon",
        "mobility": 96,
        "intellect": 62,
        "resilience": 93,
        "recovery": 95,
        "strength": 41,
        "discipline": 51
      }]
